# Generated by Django 3.1.6 on 2021-05-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('feedback', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('contact_email', models.CharField(max_length=64, null=True)),
                ('Major', models.CharField(max_length=64)),
                ('CourseNumber', models.IntegerField(null=True)),
                ('has_group1', models.BooleanField(default=False)),
                ('time_management', models.IntegerField(null=True)),
                ('time_zone', models.IntegerField(null=True)),
                ('zoom_preference', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
