# Generated by Django 3.1.6 on 2021-05-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='zoom_preference',
        ),
    ]
