# Generated by Django 3.1.6 on 2021-02-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact_email',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wants_totalk',
            field=models.BooleanField(default=False),
        ),
    ]
