# Generated by Django 3.1.6 on 2021-04-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0002_auto_20210227_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='destination_city',
            new_name='Course1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='taking_passengers',
            new_name='has_group1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='destination_state',
        ),
        migrations.RemoveField(
            model_name='person',
            name='origination',
        ),
        migrations.RemoveField(
            model_name='person',
            name='seats_available',
        ),
        migrations.RemoveField(
            model_name='person',
            name='time',
        ),
        migrations.RemoveField(
            model_name='person',
            name='wants_totalk',
        ),
    ]
