# Generated by Django 3.1.6 on 2021-05-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0002_auto_20210506_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='zoom_preference',
            field=models.IntegerField(null=True),
        ),
    ]
