# Generated by Django 3.1.6 on 2021-04-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0003_auto_20210418_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Course1',
            new_name='Major',
        ),
        migrations.AddField(
            model_name='person',
            name='CourseNumber',
            field=models.IntegerField(null=True),
        ),
    ]
