# Generated by Django 3.1.6 on 2021-05-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0004_auto_20210427_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='in_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='time_management',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='time_zone',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
