# Generated by Django 3.1.6 on 2021-05-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0007_auto_20210503_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='in_person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='time_management',
        ),
        migrations.RemoveField(
            model_name='person',
            name='time_zone',
        ),
    ]
