# Generated by Django 3.1.6 on 2021-05-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0008_auto_20210503_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='time_management',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='time_zone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='zoom_preference',
            field=models.IntegerField(null=True),
        ),
    ]
