# Generated by Django 3.1.6 on 2021-05-05 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 5, 18, 17, 59, 365875)),
        ),
    ]
