# Generated by Django 3.1.6 on 2021-05-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0011_person_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(),
        ),
    ]
