# Generated by Django 3.1.6 on 2021-05-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0012_auto_20210505_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
