# Generated by Django 3.1.6 on 2021-05-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0013_auto_20210505_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
